### ISSUE TITLE
Deploy stage

### ISSUE THREAD

**Issue by skinofstars** [jayef0/chalice-extended-action#3]
Any thoughts on how one might pass the `--stage prod` flag in this? I tried on the OPERATION but didn't seem to work.

**Comment by jayef0** [comment]
Currently, there is no way to set the stage parameter. I will add the feature to set the stage parameter. The next version will be released in the next days. I will inform you in this issue, when the new version is available.

**Comment by jayef0** [comment]
Feature is now implemented. Feel free to test it.
